// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxKBUkjAWrz1JnKFYhe3KNVAbmwPxkZaA',
    appId: '1:167259198339:android:b72c92f5f49edd702c1cb6',
    messagingSenderId: '167259198339',
    projectId: 'shopista-0001',
    storageBucket: 'shopista-0001.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY3rwQ1vxC1k6hMb_Qx7BErCnbnvYlze4',
    appId: '1:167259198339:web:f64aa83a88e82af02c1cb6',
    messagingSenderId: '167259198339',
    projectId: 'shopista-0001',
    authDomain: 'shopista-0001.firebaseapp.com',
    storageBucket: 'shopista-0001.firebasestorage.app',
    measurementId: 'G-V812YX6FQG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQxtU-a3jMkBQUyVM83Q17Lx0bwWbfiTU',
    appId: '1:167259198339:ios:22ae8328bbb1cb792c1cb6',
    messagingSenderId: '167259198339',
    projectId: 'shopista-0001',
    storageBucket: 'shopista-0001.firebasestorage.app',
    iosClientId: '167259198339-gtjg0n8lk0bdf23dffs97csp6gk9m4m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQxtU-a3jMkBQUyVM83Q17Lx0bwWbfiTU',
    appId: '1:167259198339:ios:22ae8328bbb1cb792c1cb6',
    messagingSenderId: '167259198339',
    projectId: 'shopista-0001',
    storageBucket: 'shopista-0001.firebasestorage.app',
    iosClientId: '167259198339-gtjg0n8lk0bdf23dffs97csp6gk9m4m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY3rwQ1vxC1k6hMb_Qx7BErCnbnvYlze4',
    appId: '1:167259198339:web:f95110ceb356e0bf2c1cb6',
    messagingSenderId: '167259198339',
    projectId: 'shopista-0001',
    authDomain: 'shopista-0001.firebaseapp.com',
    storageBucket: 'shopista-0001.firebasestorage.app',
    measurementId: 'G-RDP1MFGTRE',
  );

}